{
  "collections": [
    {
      "name": "Buttons",
      "label": "Buttons List",
      "file": "index.html",
      "selector": ".button-stack .button",
      "fields": [
        {
          "name": "link",
          "label": "Link URL",
          "type": "attribute",
          "attribute": "href"
        },
        {
          "name": "label",
          "label": "Button Name",
          "type": "text"
        },
        {
          "name": "brand",
          "label": "Brand Class",
          "type": "attribute",
          "attribute": "class"
        }
      ],
      "actions": ["add", "edit", "delete"]
    }
  ]
}
