content:
  - name: button_config
    label: Button Configuration
    type: file
    path: button.yml
    format: yaml
    fields:
      - name: buttons
        label: Buttons
        type: object
        list: true
        fields:
          - name: name
            label: Button Name
            type: string
            required: true
          - name: url
            label: URL
            type: string
            required: true
            pattern: { regex: '^https?://.*', message: 'Must be a valid URL' }
          - name: icon_class
            label: Icon Class
            type: string
            default: "default-icon"
      - name: button_stack
        label: Button Stack
        type: object
        list: true
        fields:
          - name: name
            label: Button Name
            type: string
            required: true
          - name: url
            label: URL
            type: string
            required: true
            pattern: { regex: '^https?://.*', message: 'Must be a valid URL' }
          - name: icon_class
            label: Icon Class
            type: string
            default: "default-icon"